Subfield z (|z) in the ISBN tag and LCCN tag is for canceled or invalid numbers.  Some systems are able to identify an invalid number in the ISBN tag when the last digit or check digit does not properly compute, thus it is an invalid ISBN number.  The Pioneer system does not identify such numbers.  An ISBN and/or a LCCN should not be listed in subfield a (|a) in more than one record.

If you have two or more records with the same LCCN it is easy to identify which is correct by checking the Library of Congress catalog at http://catalog.loc.gov/.  The LCCN is the Library of Congress’ control number or system number, thus any number is unique to one record at LC.  Because of this uniqueness it is one of the most important match keys for trying to detect duplicate records.  Unfortunately publishers do not understand this uniqueness and often you will find that publishers list the same LCCN in subsequent editions of books.  (Note: mass market paperbacks are never cataloged by LC.)  If you find a LCCN that is not correct but is listed in an item in hand you can list the LCCN in a bib by using subfield z (|z) to identify it as being in an item but not being correct or being invalid – thus it can still be a “match point.”

ISBNs are assigned by publishers and are supposed to be unique.  Unfortunately not all publishers understand this and will print the same ISBN in different editions or sometimes simply make a mistake and print it in two completely different works.  Publishers also print multiple ISBNs in items (often for different formats).  Multiple records with the same ISBN are a bit trickier than LCCNs as there is no definitive database or catalog to check these against.  If completely different records are found with the same ISBN then the safest way is to change each instance to subfield z (|z) to reflect the incorrectness of this ISBN.  [If you are cataloging an item and want to include the ISBN for other formats (e.g. large print, sound recordings, etc.) on the bib then you need to also list them as subfield z (|z) to reflect that they are not correct for this particular bib and item.]
 
It is important to also note that you made a change in a record by adding your code (e.g. OCLC code) to the 040 tag in subfield d (|d).  

The importance and key to correctly coding subfield z (|z) in the ISBN & LCCN is for matching purposes, both by hand and by machine.
